title: MATH 80600A - Machine Learning II<br>Deep Learning and Applications
description: HEC Montr√©al
google_analytics:
theme: jekyll-theme-cayman


url: "https://chao1224.github.io/"
baseurl: "/Math80600A_2021W"
#baseurl: "/"